FirstHomeWork/Controllers/CustomContactController.cs
using FirstHomeWork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstHomeWork.Controllers
{
    public class CustomContactController : Controller
    {
        //客戶資料Entities db = new 客戶資料Entities();
        客戶聯絡人Repository rpo = RepositoryHelper.Get客戶聯絡人Repository();
        客戶資料Repository rpoBasic = RepositoryHelper.Get客戶資料Repository();
        // GET: CustomContact
        public ActionResult Index()
        {
            var data = rpo.get客戶聯絡人();
            return View(data);
        }

        [HttpPost]
        public ActionResult Index(string CustomName)
        {
            var data = rpo.Where(x => x.客戶資料.客戶名稱.Contains(CustomName)).ToList();
            return View(data);
        }

        // GET: CustomContact/Details/5
        public ActionResult Details(int id)
        {
            var data = rpo.get客戶聯絡人ByID(id);
            return View(data);
        }

        // GET: CustomContact/Create
        public ActionResult Create()
        {
            var data = new 客戶聯絡人();
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.get客戶資料();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            return View(data);
        }

        // POST: CustomContact/Create
        [HttpPost]
        public ActionResult Create(客戶聯絡人 CustomData)
        {
            var data = new 客戶聯絡人();
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.get客戶資料();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    rpo.Add(CustomData);
                    rpo.UnitOfWork.Commit();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(CustomData);
                }
            }
            return View(CustomData);
        }

        // GET: CustomContact/Edit/5
        public ActionResult Edit(int id)
        {
            var data = new 客戶聯絡人();
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.get客戶資料();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            return View(data);
        }

        // POST: CustomContact/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, 客戶聯絡人 EditedData)
        {
            var data2 = new 客戶聯絡人();
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.get客戶資料();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            if (ModelState.IsValid)
            {
                try
                {
                    var data = rpo.get客戶聯絡人ByID(id);
                    data.Email = EditedData.Email;
                    data.客戶Id = EditedData.客戶Id;
                    data.姓名 = EditedData.姓名;
                    data.手機 = EditedData.手機;
                    data.職稱 = EditedData.職稱;
                    data.電話 = EditedData.電話;
                    rpo.Edit(data);
                    rpo.UnitOfWork.Commit();

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(EditedData);
                }
            }
            return View(EditedData);
        }

        // GET: CustomContact/Delete/5
        public ActionResult Delete(int id)
        {
            var data = rpo.get客戶聯絡人ByID(id);
            data.是否已刪除 = true;
            rpo.Edit(data);
            rpo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }
        
    }
}

FirstHomeWork/Views/CustomContact/Create.cshtml
@model FirstHomeWork.Models.客戶聯絡人

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", (IEnumerable<SelectListItem>)ViewBag.List客戶id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstHomeWork/Views/CustomContact/Details.cshtml
@model FirstHomeWork.Models.客戶聯絡人

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FirstHomeWork/Views/CustomContact/Edit.cshtml
@model FirstHomeWork.Models.客戶聯絡人

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstHomeWork/Views/CustomContact/Index.cshtml
@model IEnumerable<FirstHomeWork.Models.客戶聯絡人>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "CustomContact", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <table>
        <tr>
            <td>
                @Html.DisplayName("客戶名稱")
            </td>
            <td>
                @Html.TextBox("CustomName", null, htmlAttributes: new { @class = "form-control" })
            </td>
            <td>
                <input type="submit" value="查詢" class="btn btn-default" />
            </td>
        </tr>
    </table>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.職稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.姓名)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.手機)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.電話)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.職稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.姓名)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.手機)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.電話)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}