FirstHomeWork/Controllers/CustomBankController.cs
using FirstHomeWork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstHomeWork.Controllers
{
    public class CustomBankController : Controller
    {
        客戶銀行資訊Repository rpo = RepositoryHelper.Get客戶銀行資訊Repository();
        客戶資料Repository rpoBasic = RepositoryHelper.Get客戶資料Repository();
        // GET: CustomBank
        public ActionResult Index()
        {
            
            var data = rpo.All();
            return View(data);
        }

        [HttpPost]
        public ActionResult Index(string CustomName)
        {
            var data = rpo.Where(x => x.客戶資料.客戶名稱.Contains(CustomName)).ToList();
            return View(data);
        }

        // GET: CustomBank/Details/5
        public ActionResult Details(int id)
        {
            var data = rpo.get客戶銀行資料ByID(id);
            return View(data);
        }

        // GET: CustomBank/Create
        public ActionResult Create()
        {
            var data = new 客戶銀行資訊();
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.Where(x=>x.是否已刪除==false).ToList();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            return View(data);
        }

        // POST: CustomBank/Create
        [HttpPost]
        public ActionResult Create(客戶銀行資訊 CustomData)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.Where(x => x.是否已刪除 == false).ToList();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            if(ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    rpo.Add(CustomData);
                    rpo.UnitOfWork.Commit();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(CustomData);
                }
            }
            return View(CustomData);
        }

        // GET: CustomBank/Edit/5
        public ActionResult Edit(int id)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.Where(x => x.是否已刪除 == false).ToList();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            var data = rpo.get客戶銀行資料ByID(id);
            return View(data);
        }

        // POST: CustomBank/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, 客戶銀行資訊 EditedData)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            var listid = rpoBasic.Where(x => x.是否已刪除 == false).ToList();
            foreach (var item in listid)
            {
                items.Add(new SelectListItem() { Text = item.客戶名稱.ToString(), Value = item.Id.ToString() });
            }
            ViewBag.List客戶id = items;
            if (ModelState.IsValid)
            {
                try
                {
                    var data = rpo.get客戶銀行資料ByID(id);
                    data.分行代碼 = EditedData.分行代碼;
                    data.客戶Id = EditedData.客戶Id;
                    data.帳戶名稱 = EditedData.帳戶名稱;
                    data.帳戶號碼 = EditedData.帳戶號碼;
                    data.銀行代碼 = EditedData.銀行代碼;
                    data.銀行名稱 = EditedData.銀行名稱;

                    rpo.Edit(data);
                    rpo.UnitOfWork.Commit();

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(EditedData);
                }
            }
            return View(EditedData);
        }

        // GET: CustomBank/Delete/5
        public ActionResult Delete(int id)
        {
            var data = rpo.get客戶銀行資料ByID(id);
            data.是否已刪除 = true;
            rpo.Edit(data);
            rpo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }
        
    }
}

FirstHomeWork/Views/CustomBank/Create.cshtml
@model FirstHomeWork.Models.客戶銀行資訊

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id",(IEnumerable<SelectListItem>)ViewBag.List客戶id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstHomeWork/Views/CustomBank/Details.cshtml
@model FirstHomeWork.Models.客戶銀行資訊

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FirstHomeWork/Views/CustomBank/Edit.cshtml
@model FirstHomeWork.Models.客戶銀行資訊

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", (IEnumerable<SelectListItem>)ViewBag.List客戶id, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FirstHomeWork/Views/CustomBank/Index.cshtml
@model IEnumerable<FirstHomeWork.Models.客戶銀行資訊>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "CustomBank", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <table>
        <tr>
            <td>
                @Html.DisplayName("客戶名稱")
            </td>
            <td>
                @Html.TextBox("CustomName", null, htmlAttributes: new { @class = "form-control" })
            </td>
            <td>
                <input type="submit" value="查詢" class="btn btn-default" />
            </td>
        </tr>
    </table>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.銀行名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.銀行代碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.分行代碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.帳戶名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.帳戶號碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.銀行名稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.銀行代碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.分行代碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.帳戶名稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.帳戶號碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}